### ISSUE TITLE
confused about PendingChat.fork and system prompt vs user prompt

### ISSUE THREAD

**Issue by evilsocket** [dreadnode/rigging#8]
Hi, I've started out from your bandit CTF example in order to create something [slightly different](https://github.com/evilsocket/zippo) and play with it. In the example, I see that there are two prompts, one referred as the [system prompt](https://github.com/dreadnode/rigging/blob/main/examples/bandit.py#L26) which is used for the base chat object, and then the [bigger state/context prompt](https://github.com/dreadnode/rigging/blob/main/examples/bandit.py#L370) that is used to fork the base PendingChat object (if I understood correctly).

According to the docs:

> [PendingChat.fork](https://rigging.dreadnode.io/api/chat/#rigging.chat.PendingChat.fork) will clone the current pending chat and let you maintain both the new and original object for continued processing.

But it is not clear if the state prompt is added as a second **system** prompt, or as a **user** prompt. 

In this [piece of code](https://github.com/dreadnode/rigging/blob/1b300de4ff0917a12a7de6191f8f92d57976c344/rigging/chat.py#L184), the get_prompt() return value would match the str type, in which case it seems like the context prompt is only passed as user prompt and not system. Am I correct? If that is the case, is this the desired behaviour? I'm curious if/how the system can improve if both prompts are provided as system prompts.

Thank you for your answer and great project!

**Comment by monoxgas** [comment]
I might be missing the mark, but I believe the question is related to exactly what happens if you just pass a `str` to a function which expects a message, as opposed to a full `MessageDict` or `Message` object.

Underneath almost all attempts to pass "message-like" arguments gets passed to the fit functions, where raw `str` values will always be interpreted as a user message:

https://github.com/dreadnode/rigging/blob/1b300de4ff0917a12a7de6191f8f92d57976c344/rigging/message.py#L367-L371

In other words, we'd prefer you are always explicit with what messages you are appending and what role they are taking, but using `str` values is a fast way to always create a new user message. Here is some example code:

```py
import rigging as rg

base = rg.get_generator("gpt-4-turbo").chat([
    {"role": "system", "content": "Talk like a pirate."}
])

print(base.chat.conversation)

# [system]: Talk like a pirate.

hello = base.fork("Say Hello!")
print(hello.chat.conversation)

# [system]: Talk like a pirate.
#
# [user]: Say Hello!

extend_sys = base.fork({"role": "system", "content": "But stay friendly."})
print(extend_sys.chat.conversation)

# [system]: Talk like a pirate.
# But stay friendly.

goodbye = extend_sys.fork("Say Goodbye!")
print(goodbye.chat.conversation)

# [system]: Talk like a pirate.
# But stay friendly.
#
# [user]: Say Goodbye!
```

It's also worth noting the behavior when incoming additions to a chat have the same role, they will be concatenated:

https://github.com/dreadnode/rigging/blob/1b300de4ff0917a12a7de6191f8f92d57976c344/rigging/chat.py#L533-L536

**Comment by evilsocket** [comment]
So I am correct in thinking that the bigger prompt from the State object is a user prompt (in the example, 'Say Hello!' is added as user message, not system message/prompt). I'm no expert here, but wouldn't the state prompt have a "stronger" effect if applied as system prompt instead of user prompt? What i'm suggesting is, instead of passing that str, pass a while Message object with role set to system ... makes sense?

**Comment by monoxgas** [comment]
No idea, but it sounds like a good thing to test :)

I'd imagine different models have different sensitivities to content in the system vs user roles.

**Comment by evilsocket** [comment]
got it, i'll experiment with it now that i have confirmation! thanks
